workflow:
  auto_cancel:
    on_new_commit: conservative
    on_job_failure: all

default:
  tags:
    - docker-52-1-21
    - rust

setup:
 stage: .pre
 script:
   - sudo apt-get install -y cmake

update-rust:
  stage: .pre
  script:
    - rustup update

fmt:
  script:
    - cargo fmt --all -- --check

build:
  script:
    - cargo build --verbose

clippy:
  script:
    - cargo clippy -- -D warnings

test:
  script:
    - cargo test -- --nocapture
  timeout: 10 minutes

push-image:
  stage: deploy
  script:
    - export IMAGE_NAME=registry.dnamicro.com/wallguard-server:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
