[package]
name = "nullnet-wallguard-server"
version = "0.1.10"
edition = "2021"
authors = ["Giuliano Bellini <gyulyvgc89@gmail.com>", "Anton Liashkevich <anton.liashkevich.eng@gmail.com>"]
description = "A centralized management system for network firewalls"
readme = "README.md"
#homepage = ""
repository = "https://github.com/NullNet-ai/wallguard-server"
#documentation = ""
license = "MIT"
keywords = ["firewall", "network", "manager", "centralized", "monitor"]
categories = ["network-programming"]
#include = []

[lib]
name = "libwallguard"
path = "src/lib.rs"

[[bin]]
name = "wallguard-server"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
strip = true

[dependencies]
nullnet-libdatastore = "0.1.3"
nullnet-libtoken = "0.1.0"
etherparse = "0.17.0"
tonic = { version = "0.12.3", features = ["tls", "tls-roots"] }
prost = "0.13.4"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
async-channel = "2.3.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
once_cell = "1.20.2"
chrono = "0.4.39"
nullnet-libfireparse = "0.1.5"
md5 = "0.7.0"

[build-dependencies]
tonic-build = "0.12.3"

[badges]
maintenance = { status = "actively-developed" }
