[package]
name = "wallguard-server"
version = "0.2.3"
edition = "2024"
authors = ["Giuliano Bellini <gyulyvgc99@gmail.com>", "Anton Liashkevich <anton.liashkevich.eng@gmail.com>"]
description = "A centralized management system for network firewalls"
readme = "README.md"
#homepage = ""
repository = "https://github.com/NullNet-ai/wallguard-server"
#documentation = ""
license = "MIT"
keywords = ["firewall", "network", "manager", "centralized", "monitor"]
categories = ["network-programming"]
#include = []
publish = false

[profile.release]
opt-level = 3
lto = true
strip = true

[dependencies]
nullnet-libdatastore = "0.4.4"
nullnet-libtoken = "0.2.0"
nullnet-libfireparse = "0.3.2"
nullnet-liberror = "0.1.1"
nullnet-liblogging = "0.3.0"
nullnet-libipinfo = "0.2.0"
nullnet-libtunnel = "0.3.2"
etherparse = "0.18.0"
tonic = { version = "0.13.1", features = ["_tls-any", "tls-native-roots"] }
prost = "0.13.5"
tokio = { version = "1.45.0", features = ["rt-multi-thread"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
chrono = "0.4.40"
md5 = "0.7.0"
futures = "0.3.31"
actix-web = "4.10.2"
uuid = { version = "1.15.1", features = [ "v4" ] } 
actix-cors = "0.7.1"
hyper = { version = "1.6.0", features = [ "client", "http1", "http2" ] }
hyper-util = { version = "0.1.10", features = ["client", "client-legacy", "http1"] }
http-body-util = "0.1.3"
actix-web-actors = "4.3.1"
tokio-tungstenite = "0.26.2"
actix = "0.13.5"
futures-util = "0.3.31"
rand = "0.9.0"
hex = "0.4.3"
log = "0.4.26"
clap = { version = "4.5.32", features = ["derive"] }
indexmap = "2.8.0"
tokio-rustls = "0.26.2"
rustls = "0.23.25"
webpki-roots = "0.26.8"

[build-dependencies]
tonic-build = "0.13.1"

[badges]
maintenance = { status = "actively-developed" }
