version: "3.7"

networks:
  wallmon:

volumes:
  mongodb:

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - wallmon
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb:/data/db

  wallmon-server:
    image: registry.dnamicro.com/wallmon-monitor:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID
    environment:
      MONGODB_URI: mongodb://mongodb:27017
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    container_name: wallmon-monitor
    networks:
      - wallmon
    ports:
      - "5555:5555"
