// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthorizationRequest {
    #[prost(string, tag = "1")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub device_uuid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthorizationStatus {
    #[prost(oneof = "authorization_status::State", tags = "1, 2, 3")]
    pub state: ::core::option::Option<authorization_status::State>,
}
/// Nested message and enum types in `AuthorizationStatus`.
pub mod authorization_status {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum State {
        #[prost(message, tag = "1")]
        Pending(()),
        #[prost(message, tag = "2")]
        Rejected(()),
        #[prost(message, tag = "3")]
        Approved(super::AuthorizationApproved),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthorizationApproved {
    #[prost(string, optional, tag = "1")]
    pub app_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub app_secret: ::core::option::Option<::prost::alloc::string::String>,
}
