// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshSessionData {
    #[prost(string, tag = "1")]
    pub tunnel_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub public_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WallGuardCommand {
    #[prost(oneof = "wall_guard_command::Command", tags = "1, 2, 3, 4, 5, 6, 7, 8")]
    pub command: ::core::option::Option<wall_guard_command::Command>,
}
/// Nested message and enum types in `WallGuardCommand`.
pub mod wall_guard_command {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Command {
        #[prost(string, tag = "1")]
        UpdateTokenCommand(::prost::alloc::string::String),
        #[prost(bool, tag = "2")]
        EnableNetworkMonitoringCommand(bool),
        #[prost(bool, tag = "3")]
        EnableConfigurationMonitoringCommand(bool),
        #[prost(bool, tag = "4")]
        EnableTelemetryMonitoringCommand(bool),
        #[prost(message, tag = "5")]
        OpenSshSessionCommand(super::SshSessionData),
        #[prost(string, tag = "6")]
        OpenTtySessionCommand(::prost::alloc::string::String),
        #[prost(string, tag = "7")]
        OpenUiSessionCommand(::prost::alloc::string::String),
        #[prost(message, tag = "8")]
        HeartbeatCommand(()),
    }
}
